querying_lab/querying_lab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab/', include('school_db.urls')),
    path('', RedirectView.as_view(url='/lab/'))
]

querying_lab/school_db/urls.py
from django.urls import path
from . import views


app_name = 'lab'
urlpatterns = [
    path('', views.index, name="index"),
    path('one/', views.problem_one, name="one"),
    path('two/', views.problem_two, name="two"),
    path('three/', views.problem_three, name="three"),
    path('four/', views.problem_four, name="four"),
    path('five/', views.problem_five, name="five"),
    path('six/', views.problem_six, name="six")
]

querying_lab/school_db/models.py
from django.db import models

# Create your models here.

class Instructor(models.Model):
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    hire_date = models.DateField()

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

class Student(models.Model):
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    year = models.IntegerField(default=9)
    gpa = models.FloatField()

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

class Course(models.Model):
    name = models.CharField(max_length=40)
    instructor = models.ForeignKey(Instructor, null=True, blank=True, on_delete=models.SET_NULL)
    credits = models.IntegerField()

    def __str__(self) -> str:
        return self.name

class StudentCourse(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    grade = models.CharField(max_length=20)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['student', 'course'], name='unique_student_course')
        ]

    def __str__(self) -> str:
        return f'{self.student} - {self.course}'

querying_lab/school_db/views.py
from django.shortcuts import render
from .models import Student, Instructor, Course, StudentCourse


def index(request):
    students = Student.objects.all()

    # The following line creates a list that allows you to examine the data 
    # from a Queryset in an easier to visualize way
    # It is not required for functionality!
    # Place a breakpoint on line 14, then compare 'students' and 'data_visualization'
    data_visualization = [item for item in students]

    context = {
        'students': students
    }
    return render(request, 'school/index.html', context)

def problem_one(request):  #Solved by Chris
    students_with_avg_gpa = Student.objects.filter(gpa__gt=3.0).order_by('gpa')
    # Find all students who have a GPA greater than 3.0. 
    # Order the data by highest GPAs first.
    data_visualization = [item for item in students_with_avg_gpa]
    context = {
        'students': students_with_avg_gpa
    }
    return render(request, 'school/one.html', context)

def problem_two(request): #Solved By Cole
    instructors_hired_prior_to_2010 = Instructor.objects.filter(hire_date__lt="2010-1-1").order_by('hire_date')
    # Find all instructors hired prior to 2010
    # Order by hire date
    data_visualization = [item for item in instructors_hired_prior_to_2010]

    context = {
        'instructors': instructors_hired_prior_to_2010
    }
    return render(request, 'school/two.html', context)

def problem_three(request): #solved by both of us, working on a better solution exclude() function WILL NOT WORK, idk why
    students_with_a_plus = StudentCourse.objects.filter(grade='A+')
    students_with_c_plus = StudentCourse.objects.filter(grade='C+')
    empty_array_1 = []
    empty_array_2 = []
    for student in students_with_c_plus.iterator():
        empty_array_1.append(student.student_id)
    for student in students_with_a_plus.iterator():
        empty_array_2.append(student.student_id)
    empty_array_3 = [x for x in empty_array_2 if x not in empty_array_1]
    
    final_student_list = StudentCourse.objects.filter(student_id__in=empty_array_3, grade='A+').order_by('student__first_name')
    # students_with_a_plus.exclude(student_id=empty_array)
    # students_with_a_plus = StudentCourse.objects.filter(grade='A+')
    # students_without_c_plus = students_with_a_plus.exclude(grade='C+').order_by('student__first_name')
    # Find all students who have a A+ in any class and are NOT getting a C+ in any class. 
    # Order the data by student's first name alphabetically.
    data_visualization = [item for item in final_student_list]

    context = {
        'student_courses': final_student_list
    }
    return render(request, 'school/three.html', context)

def problem_four(request): #Solved by both of us
    students_in_programming = StudentCourse.objects.filter(course_id=4).order_by('grade')
    # Find all students who are taking the Programming class. 
    # Order by their grade. 
    data_visualization = [item for item in students_in_programming]
    context = {
        'student_courses': students_in_programming
    }
    return render(request, 'school/four.html', context)

def problem_five(request): #Solved by both of us
    students_programming_a = StudentCourse.objects.filter(course_id=4, grade='A').order_by('student__last_name')
    # Find all students getting an A in the Programming class. 
    # Order by last name.
    data_visualization = [item for item in students_programming_a]
    context = {
        'student_courses': students_programming_a
    }
    return render(request, 'school/five.html', context)

def problem_six(request): #Solved? by both of us
    student_with_low_gpa = Student.objects.filter(gpa__lt=3.0)
    # Find all students with a GPA less than 3.0 who are getting an A in Programming class.
    # Order by GPA.
    data_visualization = [item for item in student_with_low_gpa]
    context = {
        'student_courses': student_with_low_gpa
    }
    return render(request, 'school/six.html', context)

################## BONUS #################
# These problems will require using Aggregate functions along with annotate()
# https://docs.djangoproject.com/en/4.0/topics/db/aggregation/
# https://docs.djangoproject.com/en/4.0/ref/models/querysets/#annotate

# Create a view function and template for each bonus problem you complete

# BONUS ONE
# Write a query to find any instructors who are only teaching one single course. Display the instructor and the course

# BONUS TWO
# Display all students along with the number of credits they are taking

# BONUS THREE
# Find all students who are getting an A in any course and average their GPAs. Display the number of students and their Average GPA

# BONUS FOUR
# Write a function that will replace student GPAs in the database with an accurate score based only on their current grades
# This may require multiple queries
# See https://www.indeed.com/career-advice/career-development/gpa-scale for a chart of what point value each grade is worth

querying_lab/school_db/templates/school/five.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Problem Five</title>
</head>
<body>
    <h1>Students with an A in Programming</h1>
    <div class="center-text">
        <h2>List of Students with an A</h2>
        <table class="center-table">
            <thead>
                <tr>
                    <th>First Name</th><th>Last Name</th><th>Grade</th>
                </tr>
            </thead>
            <tbody>
                {% for item in student_courses %}
                <tr>
                    <td>{{item.student.first_name}}</td><td>{{item.student.last_name}}</td><td>{{item.grade}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

querying_lab/school_db/templates/school/four.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Problem Four</title>
</head>
<body>
    <h1>Programming Students</h1>
    <div class="center-text">
        <h2>List of Students taking Programming</h2>
        <table class="center-table">
            <thead>
                <tr>
                    <th>First Name</th><th>Last Name</th><th>Grade</th>
                </tr>
            </thead>
            <tbody>
                {% for item in student_courses %}
                <tr>
                    <td>{{item.student.first_name}}</td><td>{{item.student.last_name}}</td><td>{{item.grade}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

querying_lab/school_db/templates/school/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>devCodeCamp Django Querying Lab</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
    <h1 class="center-text">devCodeCamp Django Querying Lab</h2>
    <nav>
        <ul>
            <li><a href="{% url 'lab:one' %}">Problem One</a></li>
            <li><a href="{% url 'lab:two' %}">Problem Two</a></li>
            <li><a href="{% url 'lab:three' %}">Problem Three</a></li>
            <li><a href="{% url 'lab:four' %}">Problem Four</a></li>
            <li><a href="{% url 'lab:five' %}">Problem Five</a></li>
            <li><a href="{% url 'lab:six' %}">Problem Six</a></li>
        </ul>
    </nav>
    <div class="center-text">
        <h2>List of all Students:</h2>
        <table class="center-table">
            <thead>
                <tr>
                    <th>First Name</th><th>Last Name</th><th>GPA</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <td>{{student.first_name}}</td><td>{{student.last_name}}</td><td>{{student.gpa}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
</body>
</html>

querying_lab/school_db/templates/school/one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Problem One</title>
</head>
<body>
    <h1>Students with GPA Over 3.0</h1>
    <div class="center-text">
        <h2>List of all Students With GPA Greater than 3.0:</h2>
        <table class="center-table">
            <thead>
                <tr>
                    <th>First Name</th><th>Last Name</th><th>GPA</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <td>{{student.first_name}}</td><td>{{student.last_name}}</td><td>{{student.gpa}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

querying_lab/school_db/templates/school/six.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Problem Six</title>
</head>
<body>
    <h1>Great Programmers under 3.0</h1>
    <div class="center-text">
        <h2>List Students with GPA under 3, and an A in Programming:</h2>
        <table class="center-table">
            <thead>
                <tr>
                    <th>First Name</th><th>Last Name</th><th>GPA</th>
                </tr>
            </thead>
            <tbody>
                {% for item in student_courses %}
                <tr>
                    <td>{{item.first_name}}</td><td>{{item.last_name}}</td><td>{{item.gpa}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

querying_lab/school_db/templates/school/three.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Problem Three</title>
</head>
<body>
    <div class="center-text">
        <h2>List of Students with A+ and not C+:</h2>
        <table class="center-table">
            <thead>
                <tr>
                    <th>First Name</th><th>Last Name</th><th>Grade</th>
                </tr>
            </thead>
            <tbody>
                {% for item in student_courses %}
                <tr>
                    <td>{{item.student.first_name}}</td><td>{{item.student.last_name}}</td><td>{{item.grade}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

querying_lab/school_db/templates/school/two.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Problem Two</title>
</head>
<body>
    <h1>Instructors Hired Before 2010</h1>
    <div class="center-text">
        <table class="center-table">
            <thead>
                <tr>
                    <th>First Name</th><th>Last Name</th><th>Date Hired</th>
                </tr>
            </thead>
            <tbody>
                {% for instructor in instructors %}
                <tr>
                    <td>{{instructor.first_name}}</td><td>{{instructor.last_name}}</td><td>{{instructor.hire_date}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>